- name: Development | Add your own key to the authorized_keys of vagrant
  authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Development | Install Git
  action: apt pkg=git state=installed

- name: Development | Ensure Ruby 1.8 is not present
  action: apt pkg=ruby1.8 state=absent

- name: Development | Ensure Ruby 1.9 is present
  action: apt pkg=ruby1.9.1 state=installed

- name: Development | Sass
  gem: name=sass state=present

- name: Development | Compass
  gem: name=compass state=present

# not sure about this, can't pass --pre
# maybe replace with "command gem install sass-globbing -v 1.0.0.rc.2 --pre"
# but this seems to work okay in the current context
- name: Development | Sass globbing
  gem: name=sass-globbing version=1.0.0.rc.2 state=present 

- name: Development | Install phpMyAdmin
  action: apt pkg=phpmyadmin state=installed

- name: Development | Set up phpMyAdmin under Apache (/phpmyadmin)
  file: src=/etc/phpmyadmin/apache.conf dest=/etc/apache2/conf.d/phpmyadmin.conf state=link

- name: Development | Make phpmyadmin accessible without password (1st occurence)
  lineinfile: dest=/etc/phpmyadmin/config.inc.php regexp='\/\/(.*)AllowNoPassword(.*)' line='\1AllowNoPassword\2' backrefs=yes backup=yes

# This is a bit of a hack. The line appears twice, only the first really needs to be changed,
# but Ansible picks the last one on the first pass... 
- name: Development | Make phpmyadmin accessible without password (2nd occurence)
  lineinfile: dest=/etc/phpmyadmin/config.inc.php regexp='\/\/(.*)AllowNoPassword(.*)' line='\1AllowNoPassword\2' backrefs=yes

- name: Development | Install phpinfo() page at /info.php
  copy: src=info.php dest=/var/www/info.php  force=no

- name: Development | Install apc page at /apc.php
  copy: src=apc.php dest=/var/www/apc.php  force=no

- name: Development | Remove /index.html 
  file: dest=/var/www/index.html state=absent

- name: Development | Capistrano
  gem: name=capistrano state=present
# action: apt pkg=capistrano state=installed

- name: Development | Capistrano dependencies
  gem: name=$item state=present
  with_items:
    - colored
    - railsless-deploy 

